In [3]:
import numpy as np

In [4]:
a = 5

In [5]:
type(a)

int

In [6]:
int_list = list(range(10))
int_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
str_list = [str(i) for i in int_list]
str_list

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [8]:
int_list * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
int_arr = np.array(int_list)
int_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
int_arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
print(int_arr.ndim)
print(int_arr.shape)
print(int_arr.size)
print(int_arr.dtype)

1
(10,)
10
int32


In [12]:
arr_2d = np.zeros((3, 5))
arr_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
int_arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [14]:
arr_2d = np.zeros((3, 5))
arr_2d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
arr_float_3d = np.ones((3, 2, 4))
arr_float_3d

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [24]:
arr_float_3d[0,:,:]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
arr_uint_3d = np.ones((3,2,4), dtype=np.uint8) * 255
arr_uint_3d

array([[[255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255]]], dtype=uint8)